name: build

on:
  push:
    branches: master
    
jobs:
  build:
    uses: MCResourcePile/overviewer-workflow/.github/workflows/build.yml@main
    with:
      DEPLOY_BRANCH: gh-pages
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
